* A Personal Emacs Configuration
This is my personal Emacs configuration, continually used and tweaked since
2020, and I am always trying to make it same behaviour on my Windows and macOS.

* Table of Content                                                              :noexport:TOC_4:
- [[#a-personal-emacs-configuration][A Personal Emacs Configuration]]
- [[#usage][Usage]]
- [[#setup][Setup]]
  - [[#key-bindings][Key Bindings]]
- [[#the-dependencies][The Dependencies]]
  - [[#flycheck][Flycheck]]
    - [[#python][Python]]
    - [[#shell][Shell]]
    - [[#yaml][YAML]]
  - [[#for-windows-platform-specifics][For Windows Platform Specifics]]
  - [[#for-macos-platform-specifics][For macOS Platform Specifics]]
    - [[#aspell][Aspell]]
- [[#windows-platform-portable-software-integration][Windows Platform: Portable Software Integration]]
  - [[#flycheck-1][Flycheck]]
    - [[#portable-python---winpython][Portable Python - WinPython]]
      - [[#python-flake8][python-flake8]]
      - [[#yaml-yamllint][yaml-yamllint]]
    - [[#portable-binary-file][Portable Binary File]]
      - [[#shellcheck][ShellCheck]]
  - [[#winpython][WinPython]]

* Usage
TODO
* Setup
Basically, following the [[#the-dependencies][The Dependencies]] section is enough to set up.

If you're a big fan of [[//haikebang.com/secure-portable.html][Portable Software on Windows Platform]] like me, please
refer to [[#windows-platform-portable-software-integration][Windows Platform: Portable Software Integration]].
** Key Bindings
Key Bindings are managed by [[https://github.com/noctuid/general.el][general.el]], and the bindings configuration can be
found from [[https://github.com/jsntn/emacs.d/blob/master/lisp/init-keybindings.el][here]].
* The Dependencies
** Flycheck
*** Python
I use =python-flake8= as Python checker, refer to =requirements.txt=.
*** Shell
I use =sh-shellcheck= as Shell checker, refer to this [[https://github.com/koalaman/shellcheck/][link]] for installation.
*** YAML
I use =yaml-yamllint= as YAML checker, refer to =requirements.txt=.
** For Windows Platform Specifics
I [[//jason.haikebang.com/posts/scoop/][started using Scoop]] to manage some of my apps, including,
- Aspell
  #+BEGIN_SRC powershell
  scoop bucket add iquiw_scoop-bucket https://github.com/iquiw/scoop-bucket
  scoop install aspell
  #+END_SRC
  (Aspell can also be implemented by MSYS2, refer to this [[https://github.com/jsntn/emacs.d/tree/b9b70469d961ee58138bff1a1ce0baf4286fb18e#use-msys2-to-manage-aspell][link]].)
- Prettier
  #+BEGIN_SRC powershell
  scoop install nodejs
  npm install -g prettier
  #+END_SRC
- ShellCheck
  #+BEGIN_SRC powershell
  scoop install shellcheck
  #+END_SRC
- shfmt
  #+BEGIN_SRC powershell
  scoop install shfmt
  #+END_SRC
** For macOS Platform Specifics
*** Aspell
Use below command to install =aspell=,

#+BEGIN_SRC shell
brew install aspell
#+END_SRC
* Windows Platform: Portable Software Integration
** Flycheck
*** Portable Python - WinPython
For the packages are installed in a portable Python like [[#winpython][WinPython]], executable
paths should be configured manually.
**** python-flake8
I.e.,
#+BEGIN_SRC lisp
(setq flycheck-python-flake8-executable "V:/WPy32-3810/python-3.8.1/Scripts/flake8.exe")
#+END_SRC
**** yaml-yamllint
I.e.,
#+BEGIN_SRC lisp
(setq flycheck-yaml-yamllint-executable "V:/WPy32-3810/python-3.8.1/Scripts/yamllint.exe")
#+END_SRC
*** Portable Binary File
**** ShellCheck
If ShellCheck is installed with pre-compiled binary file, configure the
executable path, take =V:/bin/shellcheck.exe= as example,

#+BEGIN_SRC lisp
(setq flycheck-sh-shellcheck-executable "V:/bin/shellcheck.exe")
#+END_SRC
** [[//winpython.github.io][WinPython]]
WinPython is a portable distribution of the Python programming language for
Windows.
