name: My ELPA CI

on:
  pull_request:
  push:
    paths-ignore:
    - '**.md'
    - 'README.org' 

env:
  ELPA: "local"

jobs:
  build:
    runs-on: ${{ matrix.os }}
    if: contains(github.event.head_commit.message, '#build') 
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        emacs_version:
          - 28.1

    steps:
    - uses: purcell/setup-emacs@master
      with:
        version: ${{ matrix.emacs_version }}

    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Clone myelpa
      uses: actions/checkout@v3
      with:
        repository: jsntn/myelpa
        token: ${{ secrets.ACCESS_TOKEN }}
        ref: master
        path: myelpa

    - name: Check startup
      run: |
        chmod +x ./test-startup.sh
        ./test-startup.sh
      env:
        ELPA: ${{ env.ELPA }}
